chore: SIGNAL-7217 increase timeout for Task.await_many to account for 15 sec DB timeouts + buffer
stordco/kafee pull request #112
Opened 2024-10-22 22:55 UTC by seungjinstord

## Related Ticket(s)
SIGNAL-7217

## Checklist

- [x] Code conforms to the [Elixir Styleguide](https://github.com/christopheradams/elixir_style_guide)

## Problem

Load testing in staging showed that sometimes the event handlers processed work past the default 5 second timeout of `Task.await_many`, therefore timing out. It's not frequent, but still significant, and an additional timeout to worry about.

## Details

Giving it two minutes is good enough timeout because it is well beyond the 15 second DB connection timeout, and also past the default 60 sec API call timeouts from HTTPoison or Req[/finch timeout](https://hexdocs.pm/req/Req.html#new/1).

That way there's at least a ceiling, but still enough time to do work without worrying about a 5 second timeout.

2024-10-22 23:52 UTC, btkostner requested changes

2024-10-22 23:52 UTC, btkostner commented on lib/kafee/consumer/broadway_adapter.ex
> -      Task.await_many(tasks)
Shouldn't we just do `:infinity` here to match the sync (non batching) work where we don't have any sort of timeout. I'd like to not hard code a number here because that can change _a lot_ per use case, and handling messages can be a long _long_ task.

2024-10-23 00:00 UTC, seungjinstord commented on lib/kafee/consumer/broadway_adapter.ex
> -      Task.await_many(tasks)
Ah that's a better idea. Will update!

2024-10-23 00:07 UTC, seungjinstord commented on lib/kafee/consumer/broadway_adapter.ex
> -      Task.await_many(tasks)
Updated in [27c3331](https://github.com/stordco/kafee/pull/112/commits/27c333145d52efded17b29f9016d3ec6f49d9d64)

2024-10-23 01:07 UTC, btkostner approved these changes

2024-10-23 02:27 UTC, merged